AttributeError at /rekam/update/4ebfbd42-7e63-49b6-a470-313a6c460945/b7cd7031-3a74-4e21-aa96-f4f5db4ab423/ae9181bc-c622-4e03-9191-fbd8ef0abbca/9ac67a80-b8c4-428b-872c-a1bb629e1f37/Anjing 13/f72e51f3-1461-48b6-abbe-3bd035144e3f/
'NoneType' object has no attribute 'strftime'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/rekam/update/4ebfbd42-7e63-49b6-a470-313a6c460945/b7cd7031-3a74-4e21-aa96-f4f5db4ab423/ae9181bc-c622-4e03-9191-fbd8ef0abbca/9ac67a80-b8c4-428b-872c-a1bb629e1f37/Anjing%2013/f72e51f3-1461-48b6-abbe-3bd035144e3f/
Django Version:	5.2
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'strftime'
Exception Location:	C:\Users\W-book\petclinic\kunjungan_rekam_medis\views.py, line 444, in update_kunjungan
Raised during:	kunjungan_rekam_medis.views.update_kunjungan
Python Executable:	C:\Users\W-book\petclinic\env\scripts\python.exe
Python Version:	3.13.2
Python Path:	
['C:\\Users\\W-book\\petclinic',
 'C:\\Program Files\\Python313\\python313.zip',
 'C:\\Program Files\\Python313\\DLLs',
 'C:\\Program Files\\Python313\\Lib',
 'C:\\Program Files\\Python313',
 'C:\\Users\\W-book\\petclinic\\env',
 'C:\\Users\\W-book\\petclinic\\env\\Lib\\site-packages']


 karena waktu penyelesaian none
 <!-- Waktu Selesai -->
        <div>
        <label for="timestamp_akhir" class="block mb-1 font-medium text-gray-700">
            Waktu Selesai Penanganan
        </label>
        <input type="datetime-local" id="timestamp_akhir" name="timestamp_akhir"
                step="1" 
                value="{{ current_waktu_selesai }}"
                class="w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
        {% if errors.timestamp_akhir %}
            <p class="text-red-600 text-sm mt-1">{{ errors.timestamp_akhir }}</p>
        {% endif %}
        </div>